<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <UserSecretsId>dotnet-Ots.WorkFlowService-c3debaef-00ea-42a2-9567-ef84b8c9a85f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="MetaQuotes.MT5ManagerAPI64-net2.0" Version="1755.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MetaQuotes.MT5CommonAPI64">
      <HintPath>..\..\..\..\..\Users\RJ\Downloads\mng5net-trial-main\mng5net-trial-main\MetaQuotes.MT5CommonAPI64.dll</HintPath>
    </Reference>
    <Reference Include="MetaQuotes.MT5ManagerAPI64">
      <HintPath>..\..\..\..\..\Users\RJ\Downloads\mng5net-trial-main\mng5net-trial-main\MetaQuotes.MT5ManagerAPI64.dll</HintPath>
    </Reference>
    <Reference Include="mt5api">
      <HintPath>..\..\..\..\..\Users\RJ\Downloads\mt5-net-api-trial-main\mt5-net-api-trial-main\mt5api.dll</HintPath>
    </Reference>
    <Reference Include="MT5ManagerApiNet">
      <HintPath>..\..\..\..\..\Users\RJ\Downloads\mng5net-trial-main\mng5net-trial-main\MT5ManagerApiNet.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
